name: stat230A-final-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - statsmodels
  - requests
  - tqdm
  - jupyter
  - ipykernel
  - openpyxl
  - pip
  - pip:
      - jupyterlab